# Generated by Django 4.0.4 on 2022-06-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='window',
            old_name='dlina',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='window',
            old_name='vst',
            new_name='width',
        ),
    ]
