# Generated by Django 4.0.4 on 2022-06-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_dlina_window_height_rename_vst_window_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glass', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.window')),
            ],
        ),
    ]
