# Generated by Django 4.0.4 on 2022-06-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Glass',
        ),
    ]
