# Generated by Django 4.0.4 on 2022-06-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_details_glass'),
    ]

    operations = [
        migrations.AddField(
            model_name='glass',
            name='total',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
